### ISSUE TITLE
gradle cannot build WithMaps flavour

### ISSUE THREAD

**Issue by aelmahmoudy** [microg/AppleWifiNlpBackend#4]
Since WithMaps flavour refers to Google API, I wasn't able to build the WithMaps flavour, although before using gradle I was using https://github.com/mar-v-in/MapsAPI.
Probably you need to 'gradify' your MapsAPI, then add a submodule entry for it, like you've done with UnifiedNlpApi.

**Comment by mar-v-in** [comment]
Currently the map feature is a minor and the corresponding activity can only be accessed using a shell command.

However i'll add that later once needed, the Pregrab might be an interesting feature for those without mobile data...

**Comment by mar-v-in** [comment]
WithMaps flavor has been removed in master, osmdroid is now used for the PregrabActivity
