### ISSUE TITLE
Read phone state/identity permission gets added

### ISSUE THREAD

**Issue by haarp** [microg/AppleWifiNlpBackend#6]
The permission is added despite it not being defined in the manifest.

Over at F-Droid, a dev suspects that it gets added during build because a very old SDK is targeted. Seems kinda weird to me.

Could probably do without that permission (The 1.0.1 F-Droid build didn't have it and still worked)

**Comment by mar-v-in** [comment]
Thanks for reporting, will be fixed in next release.
